// Generated by rsc types — do not edit

export interface Note {
  id: number;
  title: string;
  content: string;
  created_at: string;
  pinned: boolean;
}

export interface CreateNoteRequest {
  title: string;
  content: string;
}

export interface ApiResponse {
  success: boolean;
  message: string;
}

export interface NoteStats {
  total: number;
  pinned: number;
}
