// Generated by rsc types — do not edit

export interface Task {
  id: number;
  title: string;
  status: string;
  priority: string;
  assignee: string | null;
}

export interface TaskSummary {
  total: number;
  open: number;
  done: number;
  high_priority: number;
}
