//! TypeScript type definition generator.
//!
//! Generates `.d.ts` files from `RustScript` source files, emitting TypeScript-native
//! types for any type or enum that has `Serialize` or `Deserialize` in its `derives` list.
//! This enables type-safe IPC in Tauri apps and similar use cases where TypeScript
//! consumers need type definitions for Rust data structures.

use std::fmt::Write;
use std::path::{Path, PathBuf};

use rustscript_syntax::ast::{
    EnumDef, EnumVariant, FieldDef, ItemKind, Module, TypeAnnotation, TypeDef, TypeKind,
};
use rustscript_syntax::source::SourceMap;

use crate::error::{DriverError, Result};

/// Header comment prepended to every generated `.d.ts` file.
const HEADER: &str = "// Generated by rsc types \u{2014} do not edit";

/// Generate TypeScript type definitions from a `RustScript` source string.
///
/// Parses the source, finds all types and enums with `Serialize` or `Deserialize`
/// in their derives, and returns a `.d.ts` string with TypeScript-native types.
///
/// Returns an empty string if no serializable types are found.
#[must_use]
pub fn generate_types(source: &str, file_name: &str) -> String {
    let mut source_map = SourceMap::new();
    let file_id = source_map.add_file(file_name.to_owned(), source.to_owned());
    let (module, _diagnostics) = rustscript_parser::parse(source, file_id);
    generate_types_from_module(&module)
}

/// Generate TypeScript type definitions from a parsed `RustScript` module.
///
/// Walks the module's items, emitting `.d.ts` declarations for types and enums
/// that have `Serialize` or `Deserialize` in their derives.
#[must_use]
pub fn generate_types_from_module(module: &Module) -> String {
    let mut declarations = Vec::new();

    for item in &module.items {
        match &item.kind {
            ItemKind::TypeDef(type_def) => {
                if has_serde_derive(&type_def.derives) {
                    declarations.push(emit_type_def(type_def));
                }
            }
            ItemKind::EnumDef(enum_def) => {
                if has_serde_derive(&enum_def.derives) {
                    declarations.push(emit_enum_def(enum_def));
                }
            }
            _ => {}
        }
    }

    if declarations.is_empty() {
        return String::new();
    }

    let mut output = String::new();
    let _ = writeln!(output, "{HEADER}");
    for (i, decl) in declarations.iter().enumerate() {
        if i > 0 {
            output.push('\n');
        }
        output.push_str(decl);
    }
    output
}

/// Generate type definitions for all `.rts` files in a project directory.
///
/// Walks `src/` for `.rts` files, generates types for each, and returns
/// `(output_path, content)` pairs with the directory structure preserved.
/// The output paths are relative to the output directory (e.g., `main.d.ts`,
/// `models/user.d.ts`).
///
/// # Errors
///
/// Returns `DriverError::Io` if the source directory cannot be read or
/// individual files cannot be read.
pub fn generate_types_for_project(project_dir: &Path) -> Result<Vec<(PathBuf, String)>> {
    let src_dir = project_dir.join("src");
    if !src_dir.is_dir() {
        return Err(DriverError::Io(std::io::Error::new(
            std::io::ErrorKind::NotFound,
            format!("source directory not found: {}", src_dir.display()),
        )));
    }

    let mut results = Vec::new();
    collect_rts_types(&src_dir, &src_dir, &mut results)?;
    Ok(results)
}

/// Recursively collect `.rts` files and generate type definitions.
fn collect_rts_types(
    dir: &Path,
    src_root: &Path,
    results: &mut Vec<(PathBuf, String)>,
) -> Result<()> {
    let entries = std::fs::read_dir(dir)?;

    for entry in entries {
        let entry = entry?;
        let path = entry.path();
        if path.is_dir() {
            collect_rts_types(&path, src_root, results)?;
        } else if path.extension().is_some_and(|ext| ext == "rts") {
            let source = std::fs::read_to_string(&path)?;
            let file_name = path
                .file_name()
                .map_or("unknown.rts", |n| n.to_str().unwrap_or("unknown.rts"));
            let content = generate_types(&source, file_name);
            if !content.is_empty() {
                // Compute relative path, replacing .rts with .d.ts
                let relative = path
                    .strip_prefix(src_root)
                    .unwrap_or(&path)
                    .with_extension("d.ts");
                results.push((relative, content));
            }
        }
    }

    Ok(())
}

/// Check whether a derives list contains `Serialize` or `Deserialize`.
fn has_serde_derive(derives: &[rustscript_syntax::ast::Ident]) -> bool {
    derives
        .iter()
        .any(|d| d.name == "Serialize" || d.name == "Deserialize")
}

/// Emit a TypeScript interface declaration from a `RustScript` type definition.
fn emit_type_def(type_def: &TypeDef) -> String {
    // If it's a type alias (e.g., `type X = Partial<User>`), emit as type alias
    if let Some(type_alias) = &type_def.type_alias {
        let mut out = String::new();
        let name = &type_def.name.name;
        let generics = emit_type_params(type_def.type_params.as_ref());
        let ts_type = map_type(type_alias);
        let _ = writeln!(out, "export type {name}{generics} = {ts_type};");
        return out;
    }

    // If it has an index signature with no fields, emit as Record
    if type_def.fields.is_empty()
        && let Some(idx) = &type_def.index_signature
    {
        let mut out = String::new();
        let name = &type_def.name.name;
        let generics = emit_type_params(type_def.type_params.as_ref());
        let key_type = map_type(&idx.key_type);
        let value_type = map_type(&idx.value_type);
        let _ = writeln!(
            out,
            "export type {name}{generics} = Record<{key_type}, {value_type}>;"
        );
        return out;
    }

    let mut out = String::new();
    let name = &type_def.name.name;
    let generics = emit_type_params(type_def.type_params.as_ref());
    let _ = writeln!(out, "export interface {name}{generics} {{");
    for field in &type_def.fields {
        let field_str = emit_field(field);
        let _ = writeln!(out, "  {field_str}");
    }
    let _ = writeln!(out, "}}");
    out
}

/// Emit a TypeScript type declaration from a `RustScript` enum definition.
fn emit_enum_def(enum_def: &EnumDef) -> String {
    let name = &enum_def.name.name;

    // Check if all variants are simple (string union)
    let all_simple = enum_def
        .variants
        .iter()
        .all(|v| matches!(v, EnumVariant::Simple(_, _)));

    if all_simple {
        // Emit as string union: export type Name = "a" | "b" | "c";
        let variants: Vec<String> = enum_def
            .variants
            .iter()
            .filter_map(|v| match v {
                EnumVariant::Simple(ident, _) => {
                    // The ident name is capitalized; we need the original lowercase for the string literal
                    let variant_name = lowercase_first(&ident.name);
                    Some(format!("\"{variant_name}\""))
                }
                EnumVariant::Data { .. } => None,
            })
            .collect();

        let mut out = String::new();
        let union_str = variants.join(" | ");
        let _ = writeln!(out, "export type {name} = {union_str};");
        out
    } else {
        // Discriminated union: emit as union of object types
        let variants: Vec<String> = enum_def
            .variants
            .iter()
            .map(|v| match v {
                EnumVariant::Simple(ident, _) => {
                    let variant_name = lowercase_first(&ident.name);
                    format!("{{ kind: \"{variant_name}\" }}")
                }
                EnumVariant::Data {
                    discriminant_value,
                    fields,
                    ..
                } => {
                    let mut parts = vec![format!("kind: \"{discriminant_value}\"")];
                    for field in fields {
                        parts.push(emit_field_inline(field));
                    }
                    format!("{{ {} }}", parts.join("; "))
                }
            })
            .collect();

        let mut out = String::new();
        let union_str = variants.join("\n  | ");
        let _ = writeln!(out, "export type {name} =\n  | {union_str};");
        out
    }
}

/// Emit a single interface field: `name: Type;` or `name?: Type;`.
fn emit_field(field: &FieldDef) -> String {
    let name = &field.name.name;
    let ts_type = map_type(&field.type_ann);
    if field.optional {
        format!("{name}?: {ts_type};")
    } else {
        format!("{name}: {ts_type};")
    }
}

/// Emit a field for inline use in discriminated union variants: `name: Type`.
fn emit_field_inline(field: &FieldDef) -> String {
    let name = &field.name.name;
    let ts_type = map_type(&field.type_ann);
    if field.optional {
        format!("{name}?: {ts_type}")
    } else {
        format!("{name}: {ts_type}")
    }
}

/// Emit optional generic type parameters: `<T, U>` or empty string.
fn emit_type_params(type_params: Option<&rustscript_syntax::ast::TypeParams>) -> String {
    match type_params {
        Some(tp) => {
            let params: Vec<&str> = tp.params.iter().map(|p| p.name.name.as_str()).collect();
            format!("<{}>", params.join(", "))
        }
        None => String::new(),
    }
}

/// Map a `RustScript` type annotation to a TypeScript type string.
fn map_type(ann: &TypeAnnotation) -> String {
    map_type_kind(&ann.kind)
}

/// Map a `TypeKind` to a TypeScript type string.
fn map_type_kind(kind: &TypeKind) -> String {
    match kind {
        TypeKind::Named(ident) => map_named_type(&ident.name),
        TypeKind::Void => "void".to_owned(),
        TypeKind::Never => "never".to_owned(),
        TypeKind::Unknown => "unknown".to_owned(),
        TypeKind::Generic(base, args) => map_generic_type(&base.name, args),
        TypeKind::Union(variants) => {
            let mapped: Vec<String> = variants.iter().map(map_type).collect();
            mapped.join(" | ")
        }
        TypeKind::Function(params, ret) => {
            let param_strs: Vec<String> = params
                .iter()
                .enumerate()
                .map(|(i, p)| format!("arg{i}: {}", map_type(p)))
                .collect();
            let ret_str = map_type(ret);
            format!("({}) => {ret_str}", param_strs.join(", "))
        }
        TypeKind::Tuple(elements) => {
            let mapped: Vec<String> = elements.iter().map(map_type).collect();
            format!("[{}]", mapped.join(", "))
        }
        TypeKind::Shared(inner) => map_type(inner),
        TypeKind::Readonly(inner) => {
            let inner_str = map_type(inner);
            format!("Readonly<{inner_str}>")
        }
        TypeKind::IndexSignature(idx) => {
            let key_type = map_type(&idx.key_type);
            let value_type = map_type(&idx.value_type);
            format!("Record<{key_type}, {value_type}>")
        }
        TypeKind::StringLiteral(s) => format!("\"{s}\""),
        TypeKind::Intersection(types) => {
            let mapped: Vec<String> = types.iter().map(map_type).collect();
            mapped.join(" & ")
        }
        TypeKind::Inferred => "any".to_owned(),
        TypeKind::KeyOf(inner) => {
            let inner_str = map_type(inner);
            format!("keyof {inner_str}")
        }
        TypeKind::TypeOf(ident) => format!("typeof {}", ident.name),
        TypeKind::Conditional {
            check_type,
            extends_type,
            true_type,
            false_type,
        } => {
            let check = map_type(check_type);
            let extends = map_type(extends_type);
            let t = map_type(true_type);
            let f = map_type(false_type);
            format!("{check} extends {extends} ? {t} : {f}")
        }
        TypeKind::Infer(ident) => format!("infer {}", ident.name),
        TypeKind::TupleSpread(inner) => format!("...{}", map_type(inner)),
        TypeKind::TypeGuard { .. } | TypeKind::Asserts { .. } => "boolean".to_owned(),
        TypeKind::TemplateLiteralType { quasis, types } => {
            // Emit as template literal type: `${string}suffix`
            let mut out = String::from("`");
            for (i, quasi) in quasis.iter().enumerate() {
                out.push_str(quasi);
                if i < types.len() {
                    out.push_str("${");
                    out.push_str(&map_type(&types[i]));
                    out.push('}');
                }
            }
            out.push('`');
            out
        }
        TypeKind::MappedType {
            type_param,
            constraint,
            value_type,
            ..
        } => {
            let param = &type_param.name;
            let constraint_str = map_type(constraint);
            let value_str = map_type(value_type);
            format!("{{ [K in {param} extends {constraint_str}]: {value_str} }}")
        }
        TypeKind::IndexAccess(base, index) => {
            let base_str = map_type(base);
            let index_str = map_type(index);
            format!("{base_str}[{index_str}]")
        }
    }
}

/// Map a named `RustScript` type to its TypeScript equivalent.
fn map_named_type(name: &str) -> String {
    match name {
        "i8" | "i16" | "i32" | "i64" | "u8" | "u16" | "u32" | "u64" | "f32" | "f64" | "isize"
        | "usize" => "number".to_owned(),
        "string" | "String" => "string".to_owned(),
        "bool" => "boolean".to_owned(),
        _ => name.to_owned(),
    }
}

/// Map a generic type instantiation to TypeScript.
fn map_generic_type(base: &str, args: &[TypeAnnotation]) -> String {
    match base {
        "Array" | "Vec" => {
            if let Some(inner) = args.first() {
                let inner_str = map_type(inner);
                // Use `T[]` syntax for simple types, `Array<T>` for complex ones
                if is_simple_type(&inner.kind) {
                    format!("{inner_str}[]")
                } else {
                    format!("Array<{inner_str}>")
                }
            } else {
                "any[]".to_owned()
            }
        }
        "Map" | "HashMap" | "BTreeMap" => {
            let key = args.first().map_or("string".to_owned(), map_type);
            let val = args.get(1).map_or("any".to_owned(), map_type);
            format!("Record<{key}, {val}>")
        }
        "Set" | "HashSet" | "BTreeSet" => {
            let inner = args.first().map_or("any".to_owned(), map_type);
            format!("Set<{inner}>")
        }
        "Option" => {
            let inner = args.first().map_or("any".to_owned(), map_type);
            format!("{inner} | null")
        }
        "Promise" => {
            let inner = args.first().map_or("void".to_owned(), map_type);
            format!("Promise<{inner}>")
        }
        _ => {
            // Pass through user-defined generic types
            let mapped_args: Vec<String> = args.iter().map(map_type).collect();
            format!("{base}<{}>", mapped_args.join(", "))
        }
    }
}

/// Check whether a type kind is "simple" (for deciding `T[]` vs `Array<T>`).
fn is_simple_type(kind: &TypeKind) -> bool {
    matches!(
        kind,
        TypeKind::Named(_) | TypeKind::Void | TypeKind::Never | TypeKind::Unknown
    )
}

/// Lowercase the first character of a string.
fn lowercase_first(s: &str) -> String {
    let mut chars = s.chars();
    match chars.next() {
        Some(c) => c.to_lowercase().to_string() + chars.as_str(),
        None => String::new(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn struct_with_serialize_emits_interface() {
        let source = r#"
import { Serialize } from "serde";

type User = {
    id: u32,
    name: string,
    email: string,
} derives Serialize
"#;
        let result = generate_types(source, "test.rts");
        assert!(result.contains("export interface User {"));
        assert!(result.contains("id: number;"));
        assert!(result.contains("name: string;"));
        assert!(result.contains("email: string;"));
    }

    #[test]
    fn enum_with_serialize_emits_string_union() {
        let source = r#"
import { Serialize } from "serde";

type Role = "admin" | "user" | "guest" derives Serialize
"#;
        let result = generate_types(source, "test.rts");
        assert!(result.contains("export type Role ="));
        assert!(result.contains("\"admin\""));
        assert!(result.contains("\"user\""));
        assert!(result.contains("\"guest\""));
    }

    #[test]
    fn type_without_derives_not_emitted() {
        let source = r#"
type Config = {
    debug: bool,
    port: i32,
}
"#;
        let result = generate_types(source, "test.rts");
        assert!(
            result.is_empty(),
            "Types without derives should not be emitted"
        );
    }

    #[test]
    fn optional_fields_emit_question_mark() {
        let source = r#"
import { Serialize } from "serde";

type User = {
    name: string,
    email?: string,
} derives Serialize
"#;
        let result = generate_types(source, "test.rts");
        assert!(result.contains("name: string;"));
        assert!(result.contains("email?: string;"));
    }

    #[test]
    fn numeric_types_map_to_number() {
        let source = r#"
import { Serialize } from "serde";

type Numbers = {
    a: i8,
    b: i16,
    c: i32,
    d: i64,
    e: u8,
    f: u16,
    g: u32,
    h: u64,
    i: f32,
    j: f64,
} derives Serialize
"#;
        let result = generate_types(source, "test.rts");
        assert!(result.contains("a: number;"));
        assert!(result.contains("b: number;"));
        assert!(result.contains("c: number;"));
        assert!(result.contains("d: number;"));
        assert!(result.contains("e: number;"));
        assert!(result.contains("f: number;"));
        assert!(result.contains("g: number;"));
        assert!(result.contains("h: number;"));
        assert!(result.contains("i: number;"));
        assert!(result.contains("j: number;"));
    }

    #[test]
    fn array_type_maps_to_ts_array() {
        let source = r#"
import { Serialize } from "serde";

type Tags = {
    items: Array<string>,
} derives Serialize
"#;
        let result = generate_types(source, "test.rts");
        assert!(result.contains("items: string[];"));
    }

    #[test]
    fn multiple_types_in_one_file() {
        let source = r#"
import { Serialize, Deserialize } from "serde";

type User = {
    id: u32,
    name: string,
} derives Serialize, Deserialize

type Role = "admin" | "user" derives Serialize

type Internal = {
    secret: string,
}
"#;
        let result = generate_types(source, "test.rts");
        assert!(result.contains("export interface User {"));
        assert!(result.contains("export type Role ="));
        // Internal should NOT be present
        assert!(
            !result.contains("Internal"),
            "Type without derives should not appear"
        );
    }

    #[test]
    fn generic_types_pass_through() {
        let source = r#"
import { Serialize } from "serde";

type Response<T> = {
    data: T,
    status: i32,
} derives Serialize
"#;
        let result = generate_types(source, "test.rts");
        assert!(result.contains("export interface Response<T> {"));
        assert!(result.contains("data: T;"));
        assert!(result.contains("status: number;"));
    }

    #[test]
    fn nullable_fields() {
        let source = r#"
import { Serialize } from "serde";

type User = {
    name: string,
    email: string | null,
} derives Serialize
"#;
        let result = generate_types(source, "test.rts");
        assert!(result.contains("email: string | null;"));
    }

    #[test]
    fn map_type_maps_to_record() {
        let source = r#"
import { Serialize } from "serde";

type Config = {
    settings: Map<string, string>,
} derives Serialize
"#;
        let result = generate_types(source, "test.rts");
        assert!(result.contains("settings: Record<string, string>;"));
    }

    #[test]
    fn bool_maps_to_boolean() {
        let source = r#"
import { Serialize } from "serde";

type Flags = {
    active: bool,
} derives Serialize
"#;
        let result = generate_types(source, "test.rts");
        assert!(result.contains("active: boolean;"));
    }

    #[test]
    fn tuple_types() {
        let source = r#"
import { Serialize } from "serde";

type Pair = {
    coords: [f64, f64],
} derives Serialize
"#;
        let result = generate_types(source, "test.rts");
        assert!(result.contains("coords: [number, number];"));
    }

    #[test]
    fn header_comment_present() {
        let source = r#"
import { Serialize } from "serde";

type Foo = {
    x: i32,
} derives Serialize
"#;
        let result = generate_types(source, "test.rts");
        assert!(result.starts_with("// Generated by rsc types"));
    }

    #[test]
    fn deserialize_only_also_emits() {
        let source = r#"
import { Deserialize } from "serde";

type Input = {
    value: string,
} derives Deserialize
"#;
        let result = generate_types(source, "test.rts");
        assert!(result.contains("export interface Input {"));
    }

    #[test]
    fn data_enum_emits_discriminated_union() {
        let source = r#"
import { Serialize } from "serde";

type Shape =
    | { kind: "circle", radius: f64 }
    | { kind: "rect", width: f64, height: f64 }
derives Serialize
"#;
        let result = generate_types(source, "test.rts");
        assert!(result.contains("export type Shape ="));
        assert!(result.contains("kind: \"circle\""));
        assert!(result.contains("radius: number"));
        assert!(result.contains("kind: \"rect\""));
        assert!(result.contains("width: number"));
        assert!(result.contains("height: number"));
    }

    #[test]
    fn set_type_passes_through() {
        let source = r#"
import { Serialize } from "serde";

type Collection = {
    ids: Set<u32>,
} derives Serialize
"#;
        let result = generate_types(source, "test.rts");
        assert!(result.contains("ids: Set<number>;"));
    }

    #[test]
    fn empty_source_returns_empty() {
        let result = generate_types("", "empty.rts");
        assert!(result.is_empty());
    }

    #[test]
    fn complex_nested_types() {
        let source = r#"
import { Serialize } from "serde";

type Nested = {
    users: Array<Map<string, Array<i32>>>,
} derives Serialize
"#;
        let result = generate_types(source, "test.rts");
        assert!(result.contains("export interface Nested {"));
        // Array<Map<string, Array<i32>>> → Array<Record<string, number[]>>
        assert!(result.contains("users: Array<Record<string, number[]>>;"));
    }
}
